### PR TITLE
Main Menu music

### PR DESCRIPTION
**Pull request by Blackbird88**
Because without it it's so empty :(

### CODE REVIEW

**Comment by GraionDilach** [comment]
Could you wait with this before OpenRA/OpenRA#8562 gets merged and the RA2 mod gets updated to reflect it? Right now that code would play Grinder only once and nothing more.

**Comment by Blackbird88** [comment]
No problem. I can always update it later :)

**Comment by abcdefg30** [comment]
OpenRA/OpenRA#8562 was merged.

**Comment by Blackbird88** [comment]
That was fast!

**Comment by GraionDilach** [comment]
Not really, your PR just popped up when that one was at the final steps. That took 2 weeks to be done at least. :P

**Comment by Blackbird88** [comment]
So I hit the sweet spot :D

**Pull request closed without merging**
