### PR TITLE
RA2 - Add Crater to 105mm

### PR DESCRIPTION
**Pull request by MustaphaTR**
Adds crater to Grizzly Tank's weapon.

### CODE REVIEW

**Comment by abcdefg30** [comment]
Sorry, but I didn't noticed any difference.
(Saw no smudges spawned.)

**Comment by MustaphaTR** [comment]
Updated.

**Comment by Phrohdoh** [comment]
Exception of type `System.InvalidOperationException`: Unit `smoke_m` does not have a sequence named `idle`.

**Comment by MustaphaTR** [comment]
I'm having this error too. But there is a `smoke_m` and its `idle` sequence, i'm not sure why this is giving error.
https://github.com/MustaphaTR/oramod-ra2/blob/master/sequences/misc.yaml#L301-L304

**Comment by Phrohdoh** [comment]
Our error throwing is a bit bogus in that spot, what that actually means is that the referenced file `flame3.shp` cannot be found.

**Comment by MustaphaTR** [comment]
It should be `fire03` instead of `fire3`

**Comment by MustaphaTR** [comment]
Updated.

**Comment by Phrohdoh** [comment]
Confirmed craters and crash fixed. :+1: thanks!

**Pull request merged**
