### PR TITLE
Corrected unit voices:

### PR DESCRIPTION
**Pull request by bvandenbogaard**
- Added announcement Kirov
- Spy, Demo truck and Kirov voice sequences

### CODE REVIEW

**Comment by GraionDilach** [comment]
While there's indeed a SpyCreated entry in the RA2 sound.ini, that entry was unused upon RA2 rules.ini. Please remove that.

**Comment by bvandenbogaard** [comment]
Done.

**Comment by GraionDilach** [comment]
Should've said "restore atc as attack" but that voice was unused in RA2 as well, so (y).

**Comment by Phrohdoh** [comment]
Thanks! Since I don't know how to properly set up voices, could you add shk/Tesla Trooper please? I have a branch that adds the unit to the game.

**Comment by GraionDilach** [comment]
Whoever set up Tesla Trooper, he was almost right, because only itesseb needs to be replaced with itesmoc to be an 1:1 RA2 copy (itesmoc was used as both select and move line).

**Comment by abcdefg30** [comment]
Looks also good to me. :+1: / :white_check_mark:

**Comment by abcdefg30** [comment]
Thanks. ;)

**Pull request merged**
