### PR TITLE
Fix more stuff

### PR DESCRIPTION
**Pull request by abcdefg30**
As there is no activity in #2 since 11 days, I merged some of its changes in here.
Changes:
- Removed some weapons (#2)
- Fixed the queues (#2)
- Fixed the tiles (#2)
- Fixed the bounds of all current actors
- Fixed the idle sequence of narefn

Thanks to @LipkeGu.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
`s/True/true` please.
Other than that it looks good to me. Will review on Monday or Tuesday.

**Comment by abcdefg30** [comment]
Updated.

**Comment by Phrohdoh** [comment]
My apologies @abcdefg30, I said I would look at this and I have completely forgotten.
You can expect a response tomorrow.

**Comment by Phrohdoh** [comment]
`Exception of type `System.InvalidOperationException`: Cannot locate type: OreRefineryInfo`

**Comment by Phrohdoh** [comment]
I don't have the mix archives on this machine, so I will get back to you once I fire up my desktop.

**Comment by Phrohdoh** [comment]
The queue additions look correct but we have no way to test them unfortunately.
Could you remove the `Done` status from our TODO list that reference #2 as it is clearly going nowhere?

Other than that, thanks! Merging.

**Pull request merged**
