### PR TITLE
RA2 - Added Bus, Automobile and Pickup Truck

### PR DESCRIPTION
**Pull request by MustaphaTR**
Not tried yet. Copy-Pasted from ts. Only removed cargo trait from Car and Pick and made them unable to build without devloper chats.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
Try it before you PR, because I won't test something if you haven't taken the time to.

**Comment by MustaphaTR** [comment]
Getting error when i select any of them and i don't know why.

Exception.log:

Red Alert 2 Mod at Version {DEV_VERSION}
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.Collections.Generic.KeyNotFoundException`: Verilen anahtar sözlükte yoktu.
   konum: System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   konum: OpenRA.Sound.PlayPredefined(Ruleset ruleset, Player p, Actor voicedUnit, String type, String definition, String variant, Boolean relative, WPos pos, Single volumeModifier, Boolean attenuateVolume) c:\Users\Merve-Elif\Downloads\OpenRA-bleed\OpenRA.Game\Sound\Sound.cs içinde: satır 326
   konum: OpenRA.Sound.PlayVoice(String phrase, Actor voicedUnit, String variant) c:\Users\Merve-Elif\Downloads\OpenRA-bleed\OpenRA.Game\Sound\Sound.cs içinde: satır 375
   konum: OpenRA.Selection.Combine(World world, IEnumerable`1 newSelection, Boolean isCombine, Boolean isClick) c:\Users\Merve-Elif\Downloads\OpenRA-bleed\OpenRA.Game\Selection.cs içinde: satır 62
   konum: OpenRA.Widgets.WorldInteractionControllerWidget.HandleMouseInput(MouseInput mi) c:\Users\Merve-Elif\Downloads\OpenRA-bleed\OpenRA.Game\Widgets\WorldInteractionControllerWidget.cs içinde: satır 120
   konum: OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) c:\Users\Merve-Elif\Downloads\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs içinde: satır 353
   konum: OpenRA.Widgets.Ui.HandleInput(MouseInput mi) c:\Users\Merve-Elif\Downloads\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs içinde: satır 87
   konum: OpenRA.DefaultInputHandler.<>c__DisplayClass7.<OnMouseInput>b__6() c:\Users\Merve-Elif\Downloads\OpenRA-bleed\OpenRA.Game\Input\InputHandler.cs içinde: satır 49
   konum: OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn) c:\Users\Merve-Elif\Downloads\OpenRA-bleed\OpenRA.Game\Sync.cs içinde: satır 182
   konum: OpenRA.DefaultInputHandler.OnMouseInput(MouseInput input) c:\Users\Merve-Elif\Downloads\OpenRA-bleed\OpenRA.Game\Input\InputHandler.cs içinde: satır 49
   konum: OpenRA.Renderer.Sdl2.Sdl2Input.PumpInput(IInputHandler inputHandler) c:\Users\Merve-Elif\Downloads\OpenRA-bleed\OpenRA.Renderer.Sdl2\Sdl2Input.cs içinde: satır 105
   konum: OpenRA.Renderer.Sdl2.Sdl2GraphicsDevice.PumpInput(IInputHandler inputHandler) c:\Users\Merve-Elif\Downloads\OpenRA-bleed\OpenRA.Renderer.Sdl2\Sdl2GraphicsDevice.cs içinde: satır 286
   konum: OpenRA.Graphics.Renderer.EndFrame(IInputHandler inputHandler) c:\Users\Merve-Elif\Downloads\OpenRA-bleed\OpenRA.Game\Graphics\Renderer.cs içinde: satır 156
   konum: OpenRA.Game.RenderTick() c:\Users\Merve-Elif\Downloads\OpenRA-bleed\OpenRA.Game\Game.cs içinde: satır 519
   konum: OpenRA.Game.Loop() c:\Users\Merve-Elif\Downloads\OpenRA-bleed\OpenRA.Game\Game.cs içinde: satır 620
   konum: OpenRA.Game.Run() c:\Users\Merve-Elif\Downloads\OpenRA-bleed\OpenRA.Game\Game.cs içinde: satır 638
   konum: OpenRA.Program.Run(String[] args) c:\Users\Merve-Elif\Downloads\OpenRA-bleed\OpenRA.Game\Support\Program.cs içinde: satır 111
   konum: OpenRA.Program.Main(String[] args) c:\Users\Merve-Elif\Downloads\OpenRA-bleed\OpenRA.Game\Support\Program.cs içinde: satır 39

**Comment by bvandenbogaard** [comment]
It's because there isn't a Move audio variant defined in voices. See if adding "Move:" to the CarVoice definition without a value helps. You can do this in voices.yaml.

**Comment by MustaphaTR** [comment]
@bvandenbogaard Nope there is. And this was happening before i add selectable trait.

**Comment by Phrohdoh** [comment]
Has this been resolved?

**Comment by MustaphaTR** [comment]
Updated.

**Comment by Phrohdoh** [comment]
This PR causes:
```
Platform is OSX
Using SDL 2 with OpenGL renderer
Desktop resolution: 1440x900
Using resolution: 1024x768
Detected OpenGL version: 2.1
Using OpenAL sound engine
Using default device
Available mods:
	cnc: Tiberian Dawn ({DEV_VERSION})
	d2k: Dune 2000 ({DEV_VERSION})
	modchooser: Mod Chooser ({DEV_VERSION})
	ra: Red Alert ({DEV_VERSION})
	ra2: Red Alert 2 ({DEV_VERSION})
	ts: Tiberian Sun ({DEV_VERSION})
Loading mod: ra2
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object
  at OpenRA.Graphics.Theater..ctor (OpenRA.TileSet tileset) [0x00136] in /Users/thill/projects/openra/OpenRA.Game//Graphics/Theater.cs:63 
  at OpenRA.Graphics.WorldRenderer..ctor (OpenRA.World world) [0x000c3] in /Users/thill/projects/openra/OpenRA.Game//Graphics/WorldRenderer.cs:63 
  at OpenRA.Game.StartGame (System.String mapUID, WorldType type) [0x000ad] in /Users/thill/projects/openra/OpenRA.Game//Game.cs:156 
  at OpenRA.Game.LoadShellMap () [0x00019] in /Users/thill/projects/openra/OpenRA.Game//Game.cs:380 
  at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame (OpenRA.Arguments args) [0x0022e] in /Users/thill/projects/openra/OpenRA.Mods.Common//LoadScreens/BlankLoadScreen.cs:97 
  at OpenRA.Game.InitializeMod (System.String mod, OpenRA.Arguments args) [0x003d7] in /Users/thill/projects/openra/OpenRA.Game//Game.cs:372 
  at OpenRA.Game.Initialize (OpenRA.Arguments args) [0x002d0] in /Users/thill/projects/openra/OpenRA.Game//Game.cs:264 
  at OpenRA.Program.Run (System.String[] args) [0x00007] in /Users/thill/projects/openra/OpenRA.Game//Support/Program.cs:109 
  at OpenRA.Program.Main (System.String[] args) [0x00050] in /Users/thill/projects/openra/OpenRA.Game//Support/Program.cs:39 
```

**Comment by MustaphaTR** [comment]
I got it too. Possibelly because of a new added/changed feature it was working OK. I'll try to fix it.

**Comment by MustaphaTR** [comment]
Current RA2 mod also looks like not working. But they are giving different errors at different times.

**Comment by Phrohdoh** [comment]
The tilesets need to be reimported.

**Comment by MustaphaTR** [comment]
Working at me. Did not require any change. Only my branch is a bit outdated. Works if i make same changes on current RA2 mod.

**Comment by Phrohdoh** [comment]
After this let's focus on the actors we actually ned.

**Comment by MustaphaTR** [comment]
Rebased, working that time i tried.

**Comment by Phrohdoh** [comment]
Sorry to ask this again, but could you rebase once more?
The files have since been split and you'll need to put these actors in the correct place.

**Comment by MustaphaTR** [comment]
Rebased.

**Comment by Phrohdoh** [comment]
Everything works well and I can merge this after you remove the `Buildable` trait from these 3 actors.

Thanks! :+1:

**Pull request merged**
