### PR TITLE
Fixes Unit sounds crash

### PR DESCRIPTION
**Pull request by Blackbird88**
Might need further testing.

### CODE REVIEW

**Comment by GraionDilach** [comment]
Revert this. Bad idea. Action is the fallback value, it's also used for the Stop command and whatnot. Move should be the Action and Attack* traits should override the voice associated with them instead.

**Comment by Blackbird88** [comment]
Oh I see. It's weird it works tho.

**Comment by GraionDilach** [comment]
Yes, it will work. Keep in mind how most RA1 voices work - in them, all responses besides select were pretty much supergeneric - that's why both Move and attack ended up to be this ction as the fallback generic acknowledgement.

I'm not against this change per-se but the move responses are much more generic thereby much more suitable than the attack ones IMO.

**Comment by Blackbird88** [comment]
Well this was made to fix the crash really. Not some ultimate "unmess" solution hehe

**Comment by Phrohdoh** [comment]
`Attack` is necessary but, unfortunately, `Action` is too unless we do some overriding.

**Comment by Blackbird88** [comment]
Ah that explains it.So blank Action slots are required now.

**Comment by Phrohdoh** [comment]
No. Action fields are required unless you override voices used in yaml.

**Comment by abcdefg30** [comment]
E.g. https://github.com/OpenRA/OpenRA/commit/50e5e9df248966d564c4938613b40a6ca71ea677#diff-ce68fa997c85f3213d040866ec21e487R232

**Comment by Blackbird88** [comment]
Ah I see, but that's obviously harder heh.

**Pull request closed without merging**
