### PR TITLE
Add GI.

### PR DESCRIPTION
**Pull request by Phrohdoh**

### CODE REVIEW

**Comment by abcdefg30** [comment]
```
CustomSellValue:
	Value: 150
```
is missing (`Soylent=150`).

**Comment by Phrohdoh** [comment]
That is not what `CustomSellValue` is to be used for.

**Comment by abcdefg30** [comment]
I remember them shooting faster, but ok. :+1:

**Comment by GrayHatter** [comment]
they're missing the ability to deploy. Couldn't that feature be stolen from the MCV?

**Comment by abcdefg30** [comment]
It could, but the GI shouldn't really transform like a MCV and stealing it will probably lead into bogus behavior. @Phrohdoh has code for this issue here https://github.com/OpenRA/OpenRA/pull/7653 / https://github.com/OpenRA/OpenRA/pull/7865 .

**Pull request merged**
