### PR TITLE
Upgrade rules for BlocksBullets and WithInfantryBody changes

### PR DESCRIPTION
**Pull request by Mailaender**
* https://github.com/OpenRA/OpenRA/pull/6455
* https://github.com/OpenRA/OpenRA/pull/7638

### CODE REVIEW

**Comment by abcdefg30** [comment]
Changes look good, but I can't test atm as upstream broke our sequences.

**Comment by abcdefg30** [comment]
Merged your changes in #53.

**Comment by Mailaender** [comment]
You forgot about https://github.com/Mailaender/oramod-ra2/commit/df48ebeaef7477655faac4443a43418e09d6a4fa but whatever.

**Comment by Phrohdoh** [comment]
@abcdefg30 why couldn't this just be merged directly?

**Comment by abcdefg30** [comment]
My bad. I didn't as I couldn't start the game.
> but I can't test atm as upstream broke our sequences

**Comment by abcdefg30** [comment]
"Added" your changes back in #54. Sorry again.

**Pull request closed without merging**
