### PR TITLE
Add GAWEAP.

### PR DESCRIPTION
**Pull request by Phrohdoh**
@abcdefg30

### CODE REVIEW

**Comment by Phrohdoh** [comment]
Updated.

**Comment by Phrohdoh** [comment]
Updated again.

**Comment by Phrohdoh** [comment]
Updated thrice.

**Comment by abcdefg30** [comment]
`ExitCell` and `Bounds` don't look right.

**Comment by Phrohdoh** [comment]
I'm not counting updates anymore.

**Comment by Phrohdoh** [comment]
Works and exit is correct, though I suspect something needs to be done with the exit code.
Merging.

**Pull request merged**
